/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ejercicio4.guia2;

import javax.swing.JOptionPane;

/**
 *
 * @author valkiria
 */
public class AdministrarProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministrarProductos
     */
    public AdministrarProductos() {
        initComponents();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonNuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 204, 204));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Administracion De Productos");
        setAlignmentX(100.0F);
        setAlignmentY(100.0F);

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel6.setText("STOCK:");

        jLabel4.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel4.setText("RUBRO:");

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel3.setText("PRECIO:");

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel5.setText("DESCRIPCION:");

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa2.jpg"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.setMargin(new java.awt.Insets(2, 10, 2, 14));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel2.setText("CODIGO:");

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("ADMINISTRAR PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(botonNuevo)
                .addGap(18, 18, 18)
                .addComponent(guardar)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar))
                    .addComponent(descripcion)
                    .addComponent(categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(guardar)
                    .addComponent(botonEliminar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel7.setText("salir");

        botonSalir.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 0, 0));
        botonSalir.setText("x");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        try{
            if(!MenuDeTodoSA.inventario.isEmpty()){
                Producto p=null;
                int c=Integer.parseInt(codigo.getText());
                for (Producto prod : MenuDeTodoSA.inventario) {
                    if(prod.getCodigo()==c){
                        p=prod;
                        break;
                    }else{
                        p=new Producto(0, "", 0, 0, Categorias.SELECCIONA_UNA_CATEGORIA);
                    }
                }
                if(MenuDeTodoSA.inventario.contains(p)){
                    descripcion.setText(p.getDescripcion());
                    precio.setText(String.valueOf(p.getPrecio()));
                    stock.setText(String.valueOf(p.getStock()));
                    categoria.setSelectedItem(p.getCategoria());
                }else{
                    JOptionPane.showMessageDialog(this, "EL CODIGO INGRESADO NO TIENE PRODUCTO VINCULADO");
                    codigo.setText("");
                    descripcion.setText("");
                    stock.setText("");
                    precio.setText("");
                    categoria.setSelectedIndex(0);
                }
            }else{
                JOptionPane.showMessageDialog(this, "EL INVENTARIO AUN NO TIENE PRODUCTOS REGISTRADOS");
            }
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"EL INVENTARIO QUISO INGRESAR A UN INDICE INEXISTENTE");    
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "EL CODIGO INGRESADO NO TIENE PRODUCTO VINCULADO");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "En todos los campos debe ingresar al menos 1 valor y en los campos Codigo, Precio y Stock solo debe ingresar numeros");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ocurrio un error inesperado");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
        try{
            if(!MenuDeTodoSA.inventario.isEmpty()){
                MenuDeTodoSA.inventario.remove(new Producto((Integer.parseInt(codigo.getText())), "", 0, 0, null));
                JOptionPane.showMessageDialog(this, "Producto Eliminado Correctamente");
                limpiarCampos();
            }
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"EL INVENTARIO QUISO INGRESAR A UN INDICE INEXISTENTE");    
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "EL CONJUNTO QUISO ENTRAR A UN INDICE U OBJETO NULO");
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "En todos los campos debe ingresar al menos 1 valor y en los campos Codigo, Precio y Stock solo debe ingresar numeros");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ocurrio un error inesperado");
        }
    }//GEN-LAST:event_botonEliminarMouseClicked

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try{
            Producto prod;
            for (Producto p : MenuDeTodoSA.inventario) {
                if(p.getCodigo()==Integer.parseInt(codigo.getText())){
                    p.setDescripcion(descripcion.getText());
                    p.setCategoria((Categorias)categoria.getSelectedItem());
                    p.setPrecio(Double.parseDouble(precio.getText()));
                    p.setStock(Integer.parseInt(stock.getText()));
                    JOptionPane.showMessageDialog(this, "Producto Actualizado Correctamente");
                    codigo.setText("");
                    descripcion.setText("");
                    stock.setText("");
                    categoria.setSelectedIndex(1);
                    precio.setText("");
                    break;
                }
                
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "En todos los campos debe ingresar al menos 1 valor y en los campos Codigo, Precio y Stock solo debe ingresar numeros");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ocurrio un error inesperado");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        boolean flag=false;
        try{
            for (Producto p : MenuDeTodoSA.inventario) {
                if(p.getCodigo()==Integer.parseInt(codigo.getText())){
                    flag=true;
                    break;
                }
            }
           if(flag){
               JOptionPane.showMessageDialog(this, "El codigo de su producto ya existe en el inventario, Debe registrar el nuevo producto con otro codigo");
           }else{
               MenuDeTodoSA.inventario.add(new Producto(Integer.parseInt(codigo.getText()), descripcion.getText(), Double.parseDouble(precio.getText()), Integer.parseInt(stock.getText()), (Categorias)categoria.getSelectedItem()));
               JOptionPane.showMessageDialog(this, "Producto Agregado Correctamente");
                    codigo.setText("");
                    descripcion.setText("");
                    stock.setText("");
                    categoria.setSelectedIndex(1);
                    precio.setText("");
           }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "En todos los campos debe ingresar al menos 1 valor y en los campos Codigo, Precio y Stock solo debe ingresar numeros");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ocurrio un error inesperado");
        }
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<Categorias> categoria;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
private void cargarComboBox(){
        categoria.addItem(Categorias.SELECCIONA_UNA_CATEGORIA);
        categoria.addItem(Categorias.ELECTRONICO);
        categoria.addItem(Categorias.ALIMENTICIO);
        categoria.addItem(Categorias.FERRETERIA);
        categoria.addItem(Categorias.INDUMENTARIA);
        categoria.addItem(Categorias.PANADERIA);
        categoria.addItem(Categorias.PERFUMERIA);
    }
private void limpiarCampos(){
    codigo.setText("");
                    descripcion.setText("");
                    stock.setText("");
                    precio.setText("");
                    categoria.setSelectedIndex(0);
}
}
